version: '3'
services:
  httpd:
    image: tompouce/httpd:1.1
    ports:
     - "8081:80"
    volumes: 
      - ./conf/apache/test-laravel.conf:/etc/apache2/sites-available/test-laravel.conf
      - ./src/:/var/www/html/test-laravel
    environment:
      FPM_HOST: php:9000
    command: bash -c "a2ensite test-laravel; /usr/sbin/apache2ctl -DFOREGROUND;"
    links:
      - php
  php:    
    image: tompouce/php:1.3
    volumes: 
      - ./src/:/var/www/html/test-laravel
      - ./composer.phar/:/var/www/html/composer.phar
